services:
  - type: web
    name: toyota-mechanic-agent
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      npm install --prefix ui
      npm run build --prefix ui
    startCommand: "gunicorn server:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PORT
        value: 5000
    plan: free
    buildFilter:
      paths:
        - server.py
        - requirements.txt
        - src/**
        - ui/**
        - render.yaml
